### ISSUE TITLE
Error in departments script

### ISSUE THREAD

**Issue by ABoonstraT4E** [Tools4everBV/HelloID-Conn-Prov-Source-ADP-Workforce#22]
There is an error in the departments.ps1. There is a variable in the script that does not exist. https://github.com/Tools4everBV/HelloID-Conn-Prov-Source-ADP-Workforce/blob/main/departments.ps1#L264

on line 264 and 294
the variable $certificatePath should be replaced by $certificatePath.

**Comment by JeroenBL** [comment]
This issue has been resolved in PR: https://github.com/Tools4everBV/HelloID-Conn-Prov-Source-ADP-Workforce/pull/23
