### ISSUE TITLE
Choosing the manager

### ISSUE THREAD

**Issue by berminatorrr** [Tools4everBV/HelloID-Conn-Prov-Source-ADP-Workforce#4]
At line 291 in persons.ps1 it says:

# Assignments may contain multiple managers (per assignment). There's no way to specify which manager is primary

Actually there is a way in some implementations, because there is an extra possibility to specify who is the actual manager. After the "Must be:" I have added the break when the RelationShipCode equals (in this case) "HOOFD2". The key is to find out per implementation what that value is for the primary manager. 

Also the iteration in the for loop is hardcoded to values instead of $i:
`for ($i = 0; $i -lt $assignment.reportsTo.Length; $i++) {
                                $manager = @{
                                    FormattedName = $assignment.reportsTo[2].reportsToWorkerName.formattedName
                                    WorkerID = $assignment.reportsTo[1].workerID.idValue
                                    AssociateOID = $assignment.reportsTo[3].associateOID
                                    RelationShipCode = $assignment.reportsTo[0].reportsToRelationshipCode.longName
                                }
                            }`

Must be:
`for ($i = 0; $i -lt $assignment.reportsTo.Length; $i++) {
                                $manager = @{
                                    FormattedName = $assignment.reportsTo[$i].reportsToWorkerName.formattedName
                                    WorkerID = $assignment.reportsTo[$i].workerID.idValue
                                    AssociateOID = $assignment.reportsTo[$i].associateOID
                                    RelationShipCode = $assignment.reportsTo[$i].reportsToRelationshipCode.longName
                                }
                                if($assignment.reportsTo[$i].reportsToRelationshipCode.longName -eq "HOOFD2"){
                                    break
                                }
                            }`

**Comment by rschouten97** [comment]
Good to know!
However, as the connector has seen some changes, the code changes will look a bit different:

This part:
```
# Assignments may contain multiple managers (per assignment). There's no way to specify which manager is primary
# We always select the first one in the array
if (($assignment.reportsTo | Measure-Object).Count -ge 1) {
    $manager = ($assignment.reportsTo | Sort-Object -Descending)[0]
    $assignment | Add-Member -MemberType NoteProperty -Name "manager" -Value $manager -Force
}
```

Needs to be changed to:
```
# Assignments may contain multiple managers (per assignment). We Filter for a specific RelationShipCode, e.g. "HOOFD2"
if (($assignment.reportsTo | Measure-Object).Count -ge 1) {
    $manager = ($assignment.reportsTo | Where-Object { $_.reportsToRelationshipCode.longName -eq "$($c.MangerRelationshipCode)" })[0]
    $assignment | Add-Member -MemberType NoteProperty -Name "manager" -Value $manager -Force
}
```

Additionally, this should be added to the configuration:
```
{
    "key": "MangerRelationshipCode",
    "type": "input",
    "templateOptions": {
        "label": "Manger Relationship Code",
        "placeholder": "HOOFD2",
        "description": "The Relationship Code for the manager",
        "required": true
    }
}
```

**Comment by JeroenBL** [comment]
This issue has been open for quite some time without any recent activity. We appreciate all the feedback and contributions.

To keep our issue tracker focused and organized, we are closing this issue. If the problem persists or if there are any new developments, please feel free to reopen the issue or create a new one.

Thank you for your understanding and continued support!
